scdb_host: scdb:8080
port: 8080
protocol: http
query_result_callback_timeout: 3m
session_expire_time: 3m
session_expire_check_time: 100ms
log_level: debug
storage:
  type: mysql
  conn_str: "root:testpass@tcp(mysql:3306)/scdb?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
  spu: |
    {
        "protocol": "SEMI2K",
        "field": "FM64",
        "sigmoid_mode": "SIGMOID_REAL"
    }
party_auth:
  method: pubkey
  enable_timestamp_check: true
  validity_period: 1m
