intra_server:
  protocol: http
  host: 0.0.0.0
  port: 8080
inter_server:
  port: 8081
log_level: debug
party_code: bob
engines: ["engine_bob:8003"]
party_info_file: "/home/admin/configs/party_info.json"
private_pem_path: "/home/admin/configs/private_key.pem"
intra_host: broker_bob:8080
engine:
  timeout: 120s
  protocol: http
  content_type: application/json
storage:
  type: mysql
  conn_str: "root:__MYSQL_ROOT_PASSWD__@tcp(mysql:3306)/brokerbob?charset=utf8mb4&parseTime=True&loc=Local&interpolateParams=true"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_idle_time: 2m
  conn_max_lifetime: 5m
