// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/grm.proto

package grm

import (
	scql "github.com/secretflow/scql/pkg/proto-gen/scql"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTableMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid          string `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	RequestParty string `protobuf:"bytes,2,opt,name=request_party,json=requestParty,proto3" json:"request_party,omitempty"`
	Token        string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetTableMetaRequest) Reset() {
	*x = GetTableMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableMetaRequest) ProtoMessage() {}

func (x *GetTableMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableMetaRequest.ProtoReflect.Descriptor instead.
func (*GetTableMetaRequest) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{0}
}

func (x *GetTableMetaRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *GetTableMetaRequest) GetRequestParty() string {
	if x != nil {
		return x.RequestParty
	}
	return ""
}

func (x *GetTableMetaRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetTableMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *scql.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Schema *TableSchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *GetTableMetaResponse) Reset() {
	*x = GetTableMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTableMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableMetaResponse) ProtoMessage() {}

func (x *GetTableMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableMetaResponse.ProtoReflect.Descriptor instead.
func (*GetTableMetaResponse) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{1}
}

func (x *GetTableMetaResponse) GetStatus() *scql.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetTableMetaResponse) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ColumnDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ColumnDesc) Reset() {
	*x = ColumnDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDesc) ProtoMessage() {}

func (x *ColumnDesc) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDesc.ProtoReflect.Descriptor instead.
func (*ColumnDesc) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnDesc) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnDesc) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TableSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName    string        `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	TableName string        `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Columns   []*ColumnDesc `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{3}
}

func (x *TableSchema) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *TableSchema) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableSchema) GetColumns() []*ColumnDesc {
	if x != nil {
		return x.Columns
	}
	return nil
}

type GetEnginesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartyCodes []string `protobuf:"bytes,1,rep,name=party_codes,json=partyCodes,proto3" json:"party_codes,omitempty"`
	Token      string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetEnginesRequest) Reset() {
	*x = GetEnginesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnginesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnginesRequest) ProtoMessage() {}

func (x *GetEnginesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnginesRequest.ProtoReflect.Descriptor instead.
func (*GetEnginesRequest) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{4}
}

func (x *GetEnginesRequest) GetPartyCodes() []string {
	if x != nil {
		return x.PartyCodes
	}
	return nil
}

func (x *GetEnginesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetEnginesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      *scql.Status                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	EngineInfos []*GetEnginesResponse_EngineInfo `protobuf:"bytes,2,rep,name=engine_infos,json=engineInfos,proto3" json:"engine_infos,omitempty"`
}

func (x *GetEnginesResponse) Reset() {
	*x = GetEnginesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnginesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnginesResponse) ProtoMessage() {}

func (x *GetEnginesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnginesResponse.ProtoReflect.Descriptor instead.
func (*GetEnginesResponse) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{5}
}

func (x *GetEnginesResponse) GetStatus() *scql.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetEnginesResponse) GetEngineInfos() []*GetEnginesResponse_EngineInfo {
	if x != nil {
		return x.EngineInfos
	}
	return nil
}

type VerifyTableOwnershipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid   string `protobuf:"bytes,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *VerifyTableOwnershipRequest) Reset() {
	*x = VerifyTableOwnershipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTableOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTableOwnershipRequest) ProtoMessage() {}

func (x *VerifyTableOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTableOwnershipRequest.ProtoReflect.Descriptor instead.
func (*VerifyTableOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTableOwnershipRequest) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *VerifyTableOwnershipRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTableOwnershipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *scql.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsOwner bool         `protobuf:"varint,2,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
}

func (x *VerifyTableOwnershipResponse) Reset() {
	*x = VerifyTableOwnershipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTableOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTableOwnershipResponse) ProtoMessage() {}

func (x *VerifyTableOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTableOwnershipResponse.ProtoReflect.Descriptor instead.
func (*VerifyTableOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTableOwnershipResponse) GetStatus() *scql.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyTableOwnershipResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type GetEnginesResponse_EngineInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints  []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Credential []string `protobuf:"bytes,2,rep,name=credential,proto3" json:"credential,omitempty"`
}

func (x *GetEnginesResponse_EngineInfo) Reset() {
	*x = GetEnginesResponse_EngineInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEnginesResponse_EngineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnginesResponse_EngineInfo) ProtoMessage() {}

func (x *GetEnginesResponse_EngineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnginesResponse_EngineInfo.ProtoReflect.Descriptor instead.
func (*GetEnginesResponse_EngineInfo) Descriptor() ([]byte, []int) {
	return file_api_grm_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetEnginesResponse_EngineInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *GetEnginesResponse_EngineInfo) GetCredential() []string {
	if x != nil {
		return x.Credential
	}
	return nil
}

var File_api_grm_proto protoreflect.FileDescriptor

var file_api_grm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x1a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x6c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x22, 0x56, 0x0a,
	0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x07,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x65, 0x73,
	0x63, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x22, 0x4a, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xd3, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x48, 0x0a, 0x0c, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67,
	0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x1a, 0x4a, 0x0a, 0x0a, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x45, 0x0a, 0x1b,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x62, 0x0a, 0x1c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x32, 0xff, 0x01, 0x0a, 0x0a, 0x47, 0x52, 0x4d, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x6d,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x23,
	0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x6d, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_grm_proto_rawDescOnce sync.Once
	file_api_grm_proto_rawDescData = file_api_grm_proto_rawDesc
)

func file_api_grm_proto_rawDescGZIP() []byte {
	file_api_grm_proto_rawDescOnce.Do(func() {
		file_api_grm_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grm_proto_rawDescData)
	})
	return file_api_grm_proto_rawDescData
}

var file_api_grm_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_grm_proto_goTypes = []interface{}{
	(*GetTableMetaRequest)(nil),           // 0: grm.pb.GetTableMetaRequest
	(*GetTableMetaResponse)(nil),          // 1: grm.pb.GetTableMetaResponse
	(*ColumnDesc)(nil),                    // 2: grm.pb.ColumnDesc
	(*TableSchema)(nil),                   // 3: grm.pb.TableSchema
	(*GetEnginesRequest)(nil),             // 4: grm.pb.GetEnginesRequest
	(*GetEnginesResponse)(nil),            // 5: grm.pb.GetEnginesResponse
	(*VerifyTableOwnershipRequest)(nil),   // 6: grm.pb.VerifyTableOwnershipRequest
	(*VerifyTableOwnershipResponse)(nil),  // 7: grm.pb.VerifyTableOwnershipResponse
	(*GetEnginesResponse_EngineInfo)(nil), // 8: grm.pb.GetEnginesResponse.EngineInfo
	(*scql.Status)(nil),                   // 9: scql.pb.Status
}
var file_api_grm_proto_depIdxs = []int32{
	9, // 0: grm.pb.GetTableMetaResponse.status:type_name -> scql.pb.Status
	3, // 1: grm.pb.GetTableMetaResponse.schema:type_name -> grm.pb.TableSchema
	2, // 2: grm.pb.TableSchema.columns:type_name -> grm.pb.ColumnDesc
	9, // 3: grm.pb.GetEnginesResponse.status:type_name -> scql.pb.Status
	8, // 4: grm.pb.GetEnginesResponse.engine_infos:type_name -> grm.pb.GetEnginesResponse.EngineInfo
	9, // 5: grm.pb.VerifyTableOwnershipResponse.status:type_name -> scql.pb.Status
	0, // 6: grm.pb.GRMService.GetTableMeta:input_type -> grm.pb.GetTableMetaRequest
	4, // 7: grm.pb.GRMService.GetEngines:input_type -> grm.pb.GetEnginesRequest
	6, // 8: grm.pb.GRMService.VerifyTableOwnership:input_type -> grm.pb.VerifyTableOwnershipRequest
	1, // 9: grm.pb.GRMService.GetTableMeta:output_type -> grm.pb.GetTableMetaResponse
	5, // 10: grm.pb.GRMService.GetEngines:output_type -> grm.pb.GetEnginesResponse
	7, // 11: grm.pb.GRMService.VerifyTableOwnership:output_type -> grm.pb.VerifyTableOwnershipResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_grm_proto_init() }
func file_api_grm_proto_init() {
	if File_api_grm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTableMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnginesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnginesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTableOwnershipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTableOwnershipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEnginesResponse_EngineInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grm_proto_goTypes,
		DependencyIndexes: file_api_grm_proto_depIdxs,
		MessageInfos:      file_api_grm_proto_msgTypes,
	}.Build()
	File_api_grm_proto = out.File
	file_api_grm_proto_rawDesc = nil
	file_api_grm_proto_goTypes = nil
	file_api_grm_proto_depIdxs = nil
}
