// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.27.3
// source: api/common.proto

package scql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_INITIALIZED       JobState = 1
	JobState_JOB_RUNNING           JobState = 2
	JobState_JOB_SUCCEEDED         JobState = 3
	JobState_JOB_FAILED            JobState = 4
	JobState_JOB_CANCELED          JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_INITIALIZED",
		2: "JOB_RUNNING",
		3: "JOB_SUCCEEDED",
		4: "JOB_FAILED",
		5: "JOB_CANCELED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_INITIALIZED":       1,
		"JOB_RUNNING":           2,
		"JOB_SUCCEEDED":         3,
		"JOB_FAILED":            4,
		"JOB_CANCELED":          5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_api_common_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{0}
}

type PsiAlgorithmType int32

const (
	// auto means choosing psi type by engine
	PsiAlgorithmType_AUTO PsiAlgorithmType = 0
	PsiAlgorithmType_ECDH PsiAlgorithmType = 1
	PsiAlgorithmType_OPRF PsiAlgorithmType = 2
	PsiAlgorithmType_RR22 PsiAlgorithmType = 3
)

// Enum value maps for PsiAlgorithmType.
var (
	PsiAlgorithmType_name = map[int32]string{
		0: "AUTO",
		1: "ECDH",
		2: "OPRF",
		3: "RR22",
	}
	PsiAlgorithmType_value = map[string]int32{
		"AUTO": 0,
		"ECDH": 1,
		"OPRF": 2,
		"RR22": 3,
	}
)

func (x PsiAlgorithmType) Enum() *PsiAlgorithmType {
	p := new(PsiAlgorithmType)
	*p = x
	return p
}

func (x PsiAlgorithmType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PsiAlgorithmType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_proto_enumTypes[1].Descriptor()
}

func (PsiAlgorithmType) Type() protoreflect.EnumType {
	return &file_api_common_proto_enumTypes[1]
}

func (x PsiAlgorithmType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PsiAlgorithmType.Descriptor instead.
func (PsiAlgorithmType) EnumDescriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{1}
}

type Rr22Mode int32

const (
	Rr22Mode_UNDEFINED Rr22Mode = 0
	Rr22Mode_LOW_MODE  Rr22Mode = 1
	Rr22Mode_FAST_MODE Rr22Mode = 2
)

// Enum value maps for Rr22Mode.
var (
	Rr22Mode_name = map[int32]string{
		0: "UNDEFINED",
		1: "LOW_MODE",
		2: "FAST_MODE",
	}
	Rr22Mode_value = map[string]int32{
		"UNDEFINED": 0,
		"LOW_MODE":  1,
		"FAST_MODE": 2,
	}
)

func (x Rr22Mode) Enum() *Rr22Mode {
	p := new(Rr22Mode)
	*p = x
	return p
}

func (x Rr22Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rr22Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_proto_enumTypes[2].Descriptor()
}

func (Rr22Mode) Type() protoreflect.EnumType {
	return &file_api_common_proto_enumTypes[2]
}

func (x Rr22Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rr22Mode.Descriptor instead.
func (Rr22Mode) EnumDescriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{2}
}

// RequestHeader carries the user custom headers.
type RequestHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Custom headers used to record custom information.
	CustomHeaders map[string]string `protobuf:"bytes,1,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeader) Reset() {
	*x = RequestHeader{}
	mi := &file_api_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeader) ProtoMessage() {}

func (x *RequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeader.ProtoReflect.Descriptor instead.
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestHeader) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

type DebugOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EnablePsiDetailLog bool                   `protobuf:"varint,1,opt,name=enable_psi_detail_log,json=enablePsiDetailLog,proto3" json:"enable_psi_detail_log,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DebugOptions) Reset() {
	*x = DebugOptions{}
	mi := &file_api_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugOptions) ProtoMessage() {}

func (x *DebugOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugOptions.ProtoReflect.Descriptor instead.
func (*DebugOptions) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{1}
}

func (x *DebugOptions) GetEnablePsiDetailLog() bool {
	if x != nil {
		return x.EnablePsiDetailLog
	}
	return false
}

// (-- TODO: move SQLWarning to a proper place --)
type SQLWarning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description of the warning
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLWarning) Reset() {
	*x = SQLWarning{}
	mi := &file_api_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLWarning) ProtoMessage() {}

func (x *SQLWarning) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLWarning.ProtoReflect.Descriptor instead.
func (*SQLWarning) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{2}
}

func (x *SQLWarning) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// IOStats contains input/output statistics for a job, including bytes sent and
// received, as well as the number of send and receive actions performed.
type IOStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SendBytes     uint64                 `protobuf:"varint,1,opt,name=send_bytes,json=sendBytes,proto3" json:"send_bytes,omitempty"`
	RecvBytes     uint64                 `protobuf:"varint,2,opt,name=recv_bytes,json=recvBytes,proto3" json:"recv_bytes,omitempty"`
	SendActions   uint64                 `protobuf:"varint,3,opt,name=send_actions,json=sendActions,proto3" json:"send_actions,omitempty"`
	RecvActions   uint64                 `protobuf:"varint,4,opt,name=recv_actions,json=recvActions,proto3" json:"recv_actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOStats) Reset() {
	*x = IOStats{}
	mi := &file_api_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOStats) ProtoMessage() {}

func (x *IOStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOStats.ProtoReflect.Descriptor instead.
func (*IOStats) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{3}
}

func (x *IOStats) GetSendBytes() uint64 {
	if x != nil {
		return x.SendBytes
	}
	return 0
}

func (x *IOStats) GetRecvBytes() uint64 {
	if x != nil {
		return x.RecvBytes
	}
	return 0
}

func (x *IOStats) GetSendActions() uint64 {
	if x != nil {
		return x.SendActions
	}
	return 0
}

func (x *IOStats) GetRecvActions() uint64 {
	if x != nil {
		return x.RecvActions
	}
	return 0
}

// StageInfo provides information about an individual stage within a running
// job.
type StageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the stage.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A brief summary describing the stage
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Stage start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Personalized details that may have different structures depending on the
	// stage type.
	Details       *anypb.Any `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageInfo) Reset() {
	*x = StageInfo{}
	mi := &file_api_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageInfo) ProtoMessage() {}

func (x *StageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageInfo.ProtoReflect.Descriptor instead.
func (*StageInfo) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{4}
}

func (x *StageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StageInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *StageInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *StageInfo) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

// JobProgress provides detailed information about the progress of a running
// job.
type JobProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job start time
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The total number of stages planned for the job.
	StagesCount int32 `protobuf:"varint,2,opt,name=stages_count,json=stagesCount,proto3" json:"stages_count,omitempty"`
	// The number of stages that have been executed so far.
	ExecutedStages int32    `protobuf:"varint,3,opt,name=executed_stages,json=executedStages,proto3" json:"executed_stages,omitempty"`
	IoStats        *IOStats `protobuf:"bytes,4,opt,name=io_stats,json=ioStats,proto3" json:"io_stats,omitempty"`
	// A list of currently running stages, providing insight into which parts of
	// the job are active.
	RunningStages []*StageInfo `protobuf:"bytes,5,rep,name=running_stages,json=runningStages,proto3" json:"running_stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_api_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{5}
}

func (x *JobProgress) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *JobProgress) GetStagesCount() int32 {
	if x != nil {
		return x.StagesCount
	}
	return 0
}

func (x *JobProgress) GetExecutedStages() int32 {
	if x != nil {
		return x.ExecutedStages
	}
	return 0
}

func (x *JobProgress) GetIoStats() *IOStats {
	if x != nil {
		return x.IoStats
	}
	return nil
}

func (x *JobProgress) GetRunningStages() []*StageInfo {
	if x != nil {
		return x.RunningStages
	}
	return nil
}

type LinkConfig struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	LinkRecvTimeoutSec          int64                  `protobuf:"varint,1,opt,name=link_recv_timeout_sec,json=linkRecvTimeoutSec,proto3" json:"link_recv_timeout_sec,omitempty"`
	LinkThrottleWindowSize      int64                  `protobuf:"varint,2,opt,name=link_throttle_window_size,json=linkThrottleWindowSize,proto3" json:"link_throttle_window_size,omitempty"`
	LinkChunkedSendParallelSize int64                  `protobuf:"varint,3,opt,name=link_chunked_send_parallel_size,json=linkChunkedSendParallelSize,proto3" json:"link_chunked_send_parallel_size,omitempty"`
	HttpMaxPayloadSize          int64                  `protobuf:"varint,4,opt,name=http_max_payload_size,json=httpMaxPayloadSize,proto3" json:"http_max_payload_size,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *LinkConfig) Reset() {
	*x = LinkConfig{}
	mi := &file_api_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkConfig) ProtoMessage() {}

func (x *LinkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkConfig.ProtoReflect.Descriptor instead.
func (*LinkConfig) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{6}
}

func (x *LinkConfig) GetLinkRecvTimeoutSec() int64 {
	if x != nil {
		return x.LinkRecvTimeoutSec
	}
	return 0
}

func (x *LinkConfig) GetLinkThrottleWindowSize() int64 {
	if x != nil {
		return x.LinkThrottleWindowSize
	}
	return 0
}

func (x *LinkConfig) GetLinkChunkedSendParallelSize() int64 {
	if x != nil {
		return x.LinkChunkedSendParallelSize
	}
	return 0
}

func (x *LinkConfig) GetHttpMaxPayloadSize() int64 {
	if x != nil {
		return x.HttpMaxPayloadSize
	}
	return 0
}

type PsiConfig struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PsiCurveType int32                  `protobuf:"varint,1,opt,name=psi_curve_type,json=psiCurveType,proto3" json:"psi_curve_type,omitempty"`
	PsiType      PsiAlgorithmType       `protobuf:"varint,2,opt,name=psi_type,json=psiType,proto3,enum=scql.pb.PsiAlgorithmType" json:"psi_type,omitempty"`
	// activated when psi_type is rr22
	Rr22Mode      Rr22Mode `protobuf:"varint,3,opt,name=rr22_mode,json=rr22Mode,proto3,enum=scql.pb.Rr22Mode" json:"rr22_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsiConfig) Reset() {
	*x = PsiConfig{}
	mi := &file_api_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsiConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsiConfig) ProtoMessage() {}

func (x *PsiConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsiConfig.ProtoReflect.Descriptor instead.
func (*PsiConfig) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{7}
}

func (x *PsiConfig) GetPsiCurveType() int32 {
	if x != nil {
		return x.PsiCurveType
	}
	return 0
}

func (x *PsiConfig) GetPsiType() PsiAlgorithmType {
	if x != nil {
		return x.PsiType
	}
	return PsiAlgorithmType_AUTO
}

func (x *PsiConfig) GetRr22Mode() Rr22Mode {
	if x != nil {
		return x.Rr22Mode
	}
	return Rr22Mode_UNDEFINED
}

type LogConfig struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	EnableSessionLoggerSeparation bool                   `protobuf:"varint,1,opt,name=enable_session_logger_separation,json=enableSessionLoggerSeparation,proto3" json:"enable_session_logger_separation,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_api_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{8}
}

func (x *LogConfig) GetEnableSessionLoggerSeparation() bool {
	if x != nil {
		return x.EnableSessionLoggerSeparation
	}
	return false
}

type Placeholder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// placeholder name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// placeholder name, e.g. string, int64, float
	DataType      string `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholder) Reset() {
	*x = Placeholder{}
	mi := &file_api_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholder) ProtoMessage() {}

func (x *Placeholder) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholder.ProtoReflect.Descriptor instead.
func (*Placeholder) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{9}
}

func (x *Placeholder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Placeholder) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

type Placeholders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholders  []*Placeholder         `protobuf:"bytes,1,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placeholders) Reset() {
	*x = Placeholders{}
	mi := &file_api_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placeholders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placeholders) ProtoMessage() {}

func (x *Placeholders) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placeholders.ProtoReflect.Descriptor instead.
func (*Placeholders) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{10}
}

func (x *Placeholders) GetPlaceholders() []*Placeholder {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StringData    string                 `protobuf:"bytes,2,opt,name=string_data,json=stringData,proto3" json:"string_data,omitempty"`
	Int64Data     int64                  `protobuf:"varint,3,opt,name=int64_data,json=int64Data,proto3" json:"int64_data,omitempty"`
	FloatData     float32                `protobuf:"fixed32,4,opt,name=float_data,json=floatData,proto3" json:"float_data,omitempty"`
	BoolData      bool                   `protobuf:"varint,5,opt,name=bool_data,json=boolData,proto3" json:"bool_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_api_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_api_common_proto_rawDescGZIP(), []int{11}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetStringData() string {
	if x != nil {
		return x.StringData
	}
	return ""
}

func (x *Variable) GetInt64Data() int64 {
	if x != nil {
		return x.Int64Data
	}
	return 0
}

func (x *Variable) GetFloatData() float32 {
	if x != nil {
		return x.FloatData
	}
	return 0
}

func (x *Variable) GetBoolData() bool {
	if x != nil {
		return x.BoolData
	}
	return false
}

var File_api_common_proto protoreflect.FileDescriptor

var file_api_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x50, 0x0a, 0x0e, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x40, 0x0a, 0x12, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x41, 0x0a,
	0x0c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x31, 0x0a,
	0x15, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x73, 0x69, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x73, 0x69, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x4c, 0x6f, 0x67,
	0x22, 0x24, 0x0a, 0x0a, 0x53, 0x51, 0x4c, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x07, 0x49, 0x4f, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x63, 0x76, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x76, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xa4, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xfc, 0x01,
	0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x67,
	0x65, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x69, 0x6f, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62,
	0x2e, 0x49, 0x4f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x07, 0x69, 0x6f, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x39, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x71, 0x6c,
	0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x72,
	0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x22, 0xf3, 0x01, 0x0a,
	0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x31, 0x0a, 0x15, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x5f, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x63, 0x76, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x12, 0x39,
	0x0a, 0x19, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x16, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x68, 0x72, 0x6f, 0x74, 0x74, 0x6c, 0x65, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x44, 0x0a, 0x1f, 0x6c, 0x69, 0x6e,
	0x6b, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70,
	0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x1b, 0x6c, 0x69, 0x6e, 0x6b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x65, 0x64, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x31, 0x0a, 0x15, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12,
	0x68, 0x74, 0x74, 0x70, 0x4d, 0x61, 0x78, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x50, 0x73, 0x69, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x12, 0x24, 0x0a, 0x0e, 0x70, 0x73, 0x69, 0x5f, 0x63, 0x75, 0x72, 0x76, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x73, 0x69, 0x43, 0x75, 0x72,
	0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x70, 0x73, 0x69, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x73, 0x69, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x07, 0x70, 0x73, 0x69, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x09,
	0x72, 0x72, 0x32, 0x32, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x72, 0x32, 0x32, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x72, 0x72, 0x32, 0x32, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x54, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x47, 0x0a, 0x20, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x67, 0x67,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x1d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x53, 0x65, 0x70, 0x61, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x48, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e,
	0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x0c,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x22, 0x9a, 0x01, 0x0a,
	0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x80, 0x01, 0x0a, 0x08, 0x4a, 0x6f,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4a, 0x4f, 0x42, 0x5f, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c,
	0x49, 0x5a, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x4f, 0x42, 0x5f, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4a, 0x4f, 0x42, 0x5f, 0x53,
	0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x4f,
	0x42, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x4a, 0x4f,
	0x42, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x2a, 0x3a, 0x0a, 0x10,
	0x50, 0x73, 0x69, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x41, 0x55, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x43,
	0x44, 0x48, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x52, 0x46, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x52, 0x52, 0x32, 0x32, 0x10, 0x03, 0x2a, 0x36, 0x0a, 0x08, 0x52, 0x72, 0x32, 0x32,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x57, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x41, 0x53, 0x54, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x10, 0x02,
	0x42, 0x25, 0x0a, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x66, 0x6c,
	0x6f, 0x77, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67,
	0x65, 0x6e, 0x2f, 0x73, 0x63, 0x71, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_common_proto_rawDescOnce sync.Once
	file_api_common_proto_rawDescData = file_api_common_proto_rawDesc
)

func file_api_common_proto_rawDescGZIP() []byte {
	file_api_common_proto_rawDescOnce.Do(func() {
		file_api_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_common_proto_rawDescData)
	})
	return file_api_common_proto_rawDescData
}

var file_api_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_common_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_common_proto_goTypes = []any{
	(JobState)(0),                 // 0: scql.pb.JobState
	(PsiAlgorithmType)(0),         // 1: scql.pb.PsiAlgorithmType
	(Rr22Mode)(0),                 // 2: scql.pb.Rr22Mode
	(*RequestHeader)(nil),         // 3: scql.pb.RequestHeader
	(*DebugOptions)(nil),          // 4: scql.pb.DebugOptions
	(*SQLWarning)(nil),            // 5: scql.pb.SQLWarning
	(*IOStats)(nil),               // 6: scql.pb.IOStats
	(*StageInfo)(nil),             // 7: scql.pb.StageInfo
	(*JobProgress)(nil),           // 8: scql.pb.JobProgress
	(*LinkConfig)(nil),            // 9: scql.pb.LinkConfig
	(*PsiConfig)(nil),             // 10: scql.pb.PsiConfig
	(*LogConfig)(nil),             // 11: scql.pb.LogConfig
	(*Placeholder)(nil),           // 12: scql.pb.Placeholder
	(*Placeholders)(nil),          // 13: scql.pb.Placeholders
	(*Variable)(nil),              // 14: scql.pb.Variable
	nil,                           // 15: scql.pb.RequestHeader.CustomHeadersEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 17: google.protobuf.Any
}
var file_api_common_proto_depIdxs = []int32{
	15, // 0: scql.pb.RequestHeader.custom_headers:type_name -> scql.pb.RequestHeader.CustomHeadersEntry
	16, // 1: scql.pb.StageInfo.start_time:type_name -> google.protobuf.Timestamp
	17, // 2: scql.pb.StageInfo.details:type_name -> google.protobuf.Any
	16, // 3: scql.pb.JobProgress.start_time:type_name -> google.protobuf.Timestamp
	6,  // 4: scql.pb.JobProgress.io_stats:type_name -> scql.pb.IOStats
	7,  // 5: scql.pb.JobProgress.running_stages:type_name -> scql.pb.StageInfo
	1,  // 6: scql.pb.PsiConfig.psi_type:type_name -> scql.pb.PsiAlgorithmType
	2,  // 7: scql.pb.PsiConfig.rr22_mode:type_name -> scql.pb.Rr22Mode
	12, // 8: scql.pb.Placeholders.placeholders:type_name -> scql.pb.Placeholder
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_common_proto_init() }
func file_api_common_proto_init() {
	if File_api_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_proto_goTypes,
		DependencyIndexes: file_api_common_proto_depIdxs,
		EnumInfos:         file_api_common_proto_enumTypes,
		MessageInfos:      file_api_common_proto_msgTypes,
	}.Build()
	File_api_common_proto = out.File
	file_api_common_proto_rawDesc = nil
	file_api_common_proto_goTypes = nil
	file_api_common_proto_depIdxs = nil
}
