// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.27.3
// source: api/engine.proto

package scql

import (
	context "context"
	spu "github.com/secretflow/scql/pkg/proto-gen/spu"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// job stop reason, it maybe
	// - "Finish". Job ended normally.
	// - "Timeout". Job timeout.
	// - "Canceled". Job canceled by client, maybe triggered by CTRL+C
	// - "Error". Exception caught when running.
	// - "Killed". Killed by client.
	// - or something else.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_api_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{0}
}

func (x *StopJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StopJobRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// A message carries all job session-level (execution plan level) information.
type JobStartParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This party code.
	// It may be used to get this party information from <parties> below.
	PartyCode string `protobuf:"bytes,1,opt,name=party_code,json=partyCode,proto3" json:"party_code,omitempty"`
	// All parties that would jointly complete an execution plan.
	Parties []*JobStartParams_Party `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	// The job id
	JobId string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The spu runtime configuration.
	SpuRuntimeCfg *spu.RuntimeConfig `protobuf:"bytes,4,opt,name=spu_runtime_cfg,json=spuRuntimeCfg,proto3" json:"spu_runtime_cfg,omitempty"`
	// The query job time zone, only support time offset, like: '+08:00'
	TimeZone      string      `protobuf:"bytes,5,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	LinkCfg       *LinkConfig `protobuf:"bytes,6,opt,name=link_cfg,json=linkCfg,proto3" json:"link_cfg,omitempty"`
	PsiCfg        *PsiConfig  `protobuf:"bytes,7,opt,name=psi_cfg,json=psiCfg,proto3" json:"psi_cfg,omitempty"`
	LogCfg        *LogConfig  `protobuf:"bytes,8,opt,name=log_cfg,json=logCfg,proto3" json:"log_cfg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStartParams) Reset() {
	*x = JobStartParams{}
	mi := &file_api_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStartParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartParams) ProtoMessage() {}

func (x *JobStartParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartParams.ProtoReflect.Descriptor instead.
func (*JobStartParams) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{1}
}

func (x *JobStartParams) GetPartyCode() string {
	if x != nil {
		return x.PartyCode
	}
	return ""
}

func (x *JobStartParams) GetParties() []*JobStartParams_Party {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *JobStartParams) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStartParams) GetSpuRuntimeCfg() *spu.RuntimeConfig {
	if x != nil {
		return x.SpuRuntimeCfg
	}
	return nil
}

func (x *JobStartParams) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *JobStartParams) GetLinkCfg() *LinkConfig {
	if x != nil {
		return x.LinkCfg
	}
	return nil
}

func (x *JobStartParams) GetPsiCfg() *PsiConfig {
	if x != nil {
		return x.PsiCfg
	}
	return nil
}

func (x *JobStartParams) GetLogCfg() *LogConfig {
	if x != nil {
		return x.LogCfg
	}
	return nil
}

type GraphChecksum struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CheckGraphChecksum bool                   `protobuf:"varint,1,opt,name=check_graph_checksum,json=checkGraphChecksum,proto3" json:"check_graph_checksum,omitempty"`
	// map from rank to checksum
	// It could be used to verify and ensure that engines execute the same
	// graph.
	SubGraphChecksums  map[string]string `protobuf:"bytes,2,rep,name=sub_graph_checksums,json=subGraphChecksums,proto3" json:"sub_graph_checksums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WholeGraphChecksum string            `protobuf:"bytes,3,opt,name=whole_graph_checksum,json=wholeGraphChecksum,proto3" json:"whole_graph_checksum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GraphChecksum) Reset() {
	*x = GraphChecksum{}
	mi := &file_api_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphChecksum) ProtoMessage() {}

func (x *GraphChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphChecksum.ProtoReflect.Descriptor instead.
func (*GraphChecksum) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{2}
}

func (x *GraphChecksum) GetCheckGraphChecksum() bool {
	if x != nil {
		return x.CheckGraphChecksum
	}
	return false
}

func (x *GraphChecksum) GetSubGraphChecksums() map[string]string {
	if x != nil {
		return x.SubGraphChecksums
	}
	return nil
}

func (x *GraphChecksum) GetWholeGraphChecksum() string {
	if x != nil {
		return x.WholeGraphChecksum
	}
	return ""
}

type RunExecutionPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobParams     *JobStartParams        `protobuf:"bytes,1,opt,name=job_params,json=jobParams,proto3" json:"job_params,omitempty"`
	Graph         *SubGraph              `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	GraphChecksum *GraphChecksum         `protobuf:"bytes,3,opt,name=graph_checksum,json=graphChecksum,proto3" json:"graph_checksum,omitempty"`
	// Whether the whole execution plan on the engine should be executed
	// synchronously or asynchronously. By default, the execution plan is executed
	// synchronously.
	Async bool `protobuf:"varint,4,opt,name=async,proto3" json:"async,omitempty"`
	// Callback url, e.g.: "http://alice.com:8080/path/to/callback".
	CallbackUrl   string        `protobuf:"bytes,5,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	DebugOpts     *DebugOptions `protobuf:"bytes,6,opt,name=debug_opts,json=debugOpts,proto3" json:"debug_opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunExecutionPlanRequest) Reset() {
	*x = RunExecutionPlanRequest{}
	mi := &file_api_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunExecutionPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExecutionPlanRequest) ProtoMessage() {}

func (x *RunExecutionPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExecutionPlanRequest.ProtoReflect.Descriptor instead.
func (*RunExecutionPlanRequest) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{3}
}

func (x *RunExecutionPlanRequest) GetJobParams() *JobStartParams {
	if x != nil {
		return x.JobParams
	}
	return nil
}

func (x *RunExecutionPlanRequest) GetGraph() *SubGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *RunExecutionPlanRequest) GetGraphChecksum() *GraphChecksum {
	if x != nil {
		return x.GraphChecksum
	}
	return nil
}

func (x *RunExecutionPlanRequest) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *RunExecutionPlanRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *RunExecutionPlanRequest) GetDebugOpts() *DebugOptions {
	if x != nil {
		return x.DebugOpts
	}
	return nil
}

type RunExecutionPlanResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Output columns used to store result datas.
	OutColumns []*Tensor `protobuf:"bytes,2,rep,name=out_columns,json=outColumns,proto3" json:"out_columns,omitempty"`
	JobId      string    `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Code of party which finished the execution plan.
	PartyCode string `protobuf:"bytes,4,opt,name=party_code,json=partyCode,proto3" json:"party_code,omitempty"`
	// The number of rows affected by a select into, update, insert, or delete.
	NumRowsAffected int64 `protobuf:"varint,5,opt,name=num_rows_affected,json=numRowsAffected,proto3" json:"num_rows_affected,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunExecutionPlanResponse) Reset() {
	*x = RunExecutionPlanResponse{}
	mi := &file_api_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunExecutionPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunExecutionPlanResponse) ProtoMessage() {}

func (x *RunExecutionPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunExecutionPlanResponse.ProtoReflect.Descriptor instead.
func (*RunExecutionPlanResponse) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{4}
}

func (x *RunExecutionPlanResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RunExecutionPlanResponse) GetOutColumns() []*Tensor {
	if x != nil {
		return x.OutColumns
	}
	return nil
}

func (x *RunExecutionPlanResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunExecutionPlanResponse) GetPartyCode() string {
	if x != nil {
		return x.PartyCode
	}
	return ""
}

func (x *RunExecutionPlanResponse) GetNumRowsAffected() int64 {
	if x != nil {
		return x.NumRowsAffected
	}
	return 0
}

type QueryJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJobStatusRequest) Reset() {
	*x = QueryJobStatusRequest{}
	mi := &file_api_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobStatusRequest) ProtoMessage() {}

func (x *QueryJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJobStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{5}
}

func (x *QueryJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type QueryJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JobState      JobState               `protobuf:"varint,2,opt,name=job_state,json=jobState,proto3,enum=scql.pb.JobState" json:"job_state,omitempty"`
	Progress      *JobProgress           `protobuf:"bytes,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJobStatusResponse) Reset() {
	*x = QueryJobStatusResponse{}
	mi := &file_api_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJobStatusResponse) ProtoMessage() {}

func (x *QueryJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJobStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{6}
}

func (x *QueryJobStatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryJobStatusResponse) GetJobState() JobState {
	if x != nil {
		return x.JobState
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *QueryJobStatusResponse) GetProgress() *JobProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// After finishing running an execution plan, the Engine sends a ReportRequest
// to result callback server (for example, broker) to return the results.
type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status including whether the plan run was handled successfully,
	// if not, error message and some more information included.
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Output columns.
	OutColumns []*Tensor `protobuf:"bytes,2,rep,name=out_columns,json=outColumns,proto3" json:"out_columns,omitempty"`
	// The job_id that this execution plan belongs to.
	JobId string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Code of party which finished the plan run.
	PartyCode string `protobuf:"bytes,4,opt,name=party_code,json=partyCode,proto3" json:"party_code,omitempty"`
	// The number of rows affected by a select into, update, insert, or delete.
	NumRowsAffected int64 `protobuf:"varint,5,opt,name=num_rows_affected,json=numRowsAffected,proto3" json:"num_rows_affected,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ReportRequest) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ReportRequest) GetOutColumns() []*Tensor {
	if x != nil {
		return x.OutColumns
	}
	return nil
}

func (x *ReportRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportRequest) GetPartyCode() string {
	if x != nil {
		return x.PartyCode
	}
	return ""
}

func (x *ReportRequest) GetNumRowsAffected() int64 {
	if x != nil {
		return x.NumRowsAffected
	}
	return 0
}

type StreamingOptions struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	StreamingRowNumThreshold int64                  `protobuf:"varint,1,opt,name=streaming_row_num_threshold,json=streamingRowNumThreshold,proto3" json:"streaming_row_num_threshold,omitempty"`
	BatchRowNum              int64                  `protobuf:"varint,2,opt,name=batch_row_num,json=batchRowNum,proto3" json:"batch_row_num,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *StreamingOptions) Reset() {
	*x = StreamingOptions{}
	mi := &file_api_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingOptions) ProtoMessage() {}

func (x *StreamingOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingOptions.ProtoReflect.Descriptor instead.
func (*StreamingOptions) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{8}
}

func (x *StreamingOptions) GetStreamingRowNumThreshold() int64 {
	if x != nil {
		return x.StreamingRowNumThreshold
	}
	return 0
}

func (x *StreamingOptions) GetBatchRowNum() int64 {
	if x != nil {
		return x.BatchRowNum
	}
	return 0
}

type PsiOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PsiCurveTypes []int64                `protobuf:"varint,1,rep,packed,name=psi_curve_types,json=psiCurveTypes,proto3" json:"psi_curve_types,omitempty"`
	Rr22Mode      Rr22Mode               `protobuf:"varint,2,opt,name=rr22_mode,json=rr22Mode,proto3,enum=scql.pb.Rr22Mode" json:"rr22_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsiOptions) Reset() {
	*x = PsiOptions{}
	mi := &file_api_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsiOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsiOptions) ProtoMessage() {}

func (x *PsiOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsiOptions.ProtoReflect.Descriptor instead.
func (*PsiOptions) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{9}
}

func (x *PsiOptions) GetPsiCurveTypes() []int64 {
	if x != nil {
		return x.PsiCurveTypes
	}
	return nil
}

func (x *PsiOptions) GetRr22Mode() Rr22Mode {
	if x != nil {
		return x.Rr22Mode
	}
	return Rr22Mode_UNDEFINED
}

type NegotiationOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StreamingOptions *StreamingOptions      `protobuf:"bytes,1,opt,name=streaming_options,json=streamingOptions,proto3" json:"streaming_options,omitempty"`
	PsiOptions       *PsiOptions            `protobuf:"bytes,2,opt,name=psi_options,json=psiOptions,proto3" json:"psi_options,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NegotiationOptions) Reset() {
	*x = NegotiationOptions{}
	mi := &file_api_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationOptions) ProtoMessage() {}

func (x *NegotiationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationOptions.ProtoReflect.Descriptor instead.
func (*NegotiationOptions) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{10}
}

func (x *NegotiationOptions) GetStreamingOptions() *StreamingOptions {
	if x != nil {
		return x.StreamingOptions
	}
	return nil
}

func (x *NegotiationOptions) GetPsiOptions() *PsiOptions {
	if x != nil {
		return x.PsiOptions
	}
	return nil
}

type JobStartParams_Party struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// party code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// party name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// party host
	Host string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// party rank
	Rank int32 `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	// base64 encoded version of the DER encoded public key
	//
	// Example:
	// # 1. generate private key
	// $ openssl genpkey -algorithm ed25519 -out ed25519key.pem
	// # 2. generate public key based on above private key
	// $ openssl pkey -in ed25519key.pem -pubout
	//
	// # its output like below:
	//
	// -----BEGIN PUBLIC KEY-----
	// BASE64 ENCODED DATA
	// -----END PUBLIC KEY-----
	//
	// the field `public_key` should be the string between header "-----BEGIN
	// PUBLIC KEY-----" and footer "-----END PUBLIC KEY-----"
	PublicKey     string `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStartParams_Party) Reset() {
	*x = JobStartParams_Party{}
	mi := &file_api_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStartParams_Party) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStartParams_Party) ProtoMessage() {}

func (x *JobStartParams_Party) ProtoReflect() protoreflect.Message {
	mi := &file_api_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStartParams_Party.ProtoReflect.Descriptor instead.
func (*JobStartParams_Party) Descriptor() ([]byte, []int) {
	return file_api_engine_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JobStartParams_Party) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JobStartParams_Party) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobStartParams_Party) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *JobStartParams_Party) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *JobStartParams_Party) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

var File_api_engine_proto protoreflect.FileDescriptor

var file_api_engine_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x6c, 0x69, 0x62, 0x73, 0x70, 0x75,
	0x2f, 0x73, 0x70, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x61, 0x70, 0x69, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0xdd, 0x03, 0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62,
	0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x79, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x15,
	0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0f, 0x73, 0x70, 0x75, 0x5f, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x5f, 0x63, 0x66, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x73, 0x70, 0x75, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0d, 0x73, 0x70, 0x75, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x43, 0x66, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x7a, 0x6f, 0x6e,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e,
	0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x63, 0x66, 0x67, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x6e, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x6c, 0x69, 0x6e, 0x6b, 0x43, 0x66,
	0x67, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x73, 0x69, 0x5f, 0x63, 0x66, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x73, 0x69,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x70, 0x73, 0x69, 0x43, 0x66, 0x67, 0x12, 0x2b,
	0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x66, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x43, 0x66, 0x67, 0x1a, 0x76, 0x0a, 0x05, 0x50,
	0x61, 0x72, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x22, 0x98, 0x02, 0x0a, 0x0d, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x14, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x5d, 0x0a, 0x13, 0x73, 0x75, 0x62, 0x5f, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x2e, 0x53, 0x75, 0x62,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x11, 0x73, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x73, 0x75, 0x6d, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x5f,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x77, 0x68, 0x6f, 0x6c, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x1a, 0x44, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa8,
	0x02, 0x0a, 0x17, 0x52, 0x75, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6c, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0a, 0x6a, 0x6f,
	0x62, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x09, 0x6a, 0x6f, 0x62, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x52, 0x05, 0x67, 0x72, 0x61, 0x70, 0x68, 0x12, 0x3d, 0x0a, 0x0e, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x52, 0x0d, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x55, 0x72, 0x6c, 0x12, 0x34, 0x0a, 0x0a, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6f, 0x70, 0x74,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09,
	0x64, 0x65, 0x62, 0x75, 0x67, 0x4f, 0x70, 0x74, 0x73, 0x22, 0xd7, 0x01, 0x0a, 0x18, 0x52, 0x75,
	0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x30, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x54,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x74,
	0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61,
	0x72, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x5f, 0x72,
	0x6f, 0x77, 0x73, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x22, 0x2e, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x6a, 0x6f, 0x62, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x71,
	0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x6a,
	0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x63, 0x71, 0x6c,
	0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0xcc, 0x01, 0x0a, 0x0d, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63,
	0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x72, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x52, 0x6f, 0x77, 0x73,
	0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x75, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x1b,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x6f, 0x77, 0x5f, 0x6e, 0x75,
	0x6d, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x18, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52, 0x6f, 0x77, 0x4e,
	0x75, 0x6d, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x62,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x6f, 0x77, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x52, 0x6f, 0x77, 0x4e, 0x75, 0x6d, 0x22,
	0x64, 0x0a, 0x0a, 0x50, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a,
	0x0f, 0x70, 0x73, 0x69, 0x5f, 0x63, 0x75, 0x72, 0x76, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x70, 0x73, 0x69, 0x43, 0x75, 0x72, 0x76, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x72, 0x72, 0x32, 0x32, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x72, 0x32, 0x32, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x72, 0x72, 0x32,
	0x32, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x4e, 0x65, 0x67, 0x6f, 0x74, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x46, 0x0a, 0x11,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x10, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x34, 0x0a, 0x0b, 0x70, 0x73, 0x69, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x71, 0x6c,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a,
	0x70, 0x73, 0x69, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xf4, 0x01, 0x0a, 0x11, 0x53,
	0x43, 0x51, 0x4c, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x57, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x6c, 0x61, 0x6e, 0x12, 0x20, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x75, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x75, 0x6e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6c, 0x61,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x73, 0x63,
	0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x63,
	0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4a, 0x6f, 0x62, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07,
	0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x12, 0x17, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0x50, 0x0a, 0x14, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x38, 0x0a, 0x06, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x73, 0x63, 0x71, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x13, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e,
	0x2f, 0x73, 0x63, 0x71, 0x6c, 0x80, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_engine_proto_rawDescOnce sync.Once
	file_api_engine_proto_rawDescData = file_api_engine_proto_rawDesc
)

func file_api_engine_proto_rawDescGZIP() []byte {
	file_api_engine_proto_rawDescOnce.Do(func() {
		file_api_engine_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_engine_proto_rawDescData)
	})
	return file_api_engine_proto_rawDescData
}

var file_api_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_engine_proto_goTypes = []any{
	(*StopJobRequest)(nil),           // 0: scql.pb.StopJobRequest
	(*JobStartParams)(nil),           // 1: scql.pb.JobStartParams
	(*GraphChecksum)(nil),            // 2: scql.pb.GraphChecksum
	(*RunExecutionPlanRequest)(nil),  // 3: scql.pb.RunExecutionPlanRequest
	(*RunExecutionPlanResponse)(nil), // 4: scql.pb.RunExecutionPlanResponse
	(*QueryJobStatusRequest)(nil),    // 5: scql.pb.QueryJobStatusRequest
	(*QueryJobStatusResponse)(nil),   // 6: scql.pb.QueryJobStatusResponse
	(*ReportRequest)(nil),            // 7: scql.pb.ReportRequest
	(*StreamingOptions)(nil),         // 8: scql.pb.StreamingOptions
	(*PsiOptions)(nil),               // 9: scql.pb.PsiOptions
	(*NegotiationOptions)(nil),       // 10: scql.pb.NegotiationOptions
	(*JobStartParams_Party)(nil),     // 11: scql.pb.JobStartParams.Party
	nil,                              // 12: scql.pb.GraphChecksum.SubGraphChecksumsEntry
	(*spu.RuntimeConfig)(nil),        // 13: spu.pb.RuntimeConfig
	(*LinkConfig)(nil),               // 14: scql.pb.LinkConfig
	(*PsiConfig)(nil),                // 15: scql.pb.PsiConfig
	(*LogConfig)(nil),                // 16: scql.pb.LogConfig
	(*SubGraph)(nil),                 // 17: scql.pb.SubGraph
	(*DebugOptions)(nil),             // 18: scql.pb.DebugOptions
	(*Status)(nil),                   // 19: scql.pb.Status
	(*Tensor)(nil),                   // 20: scql.pb.Tensor
	(JobState)(0),                    // 21: scql.pb.JobState
	(*JobProgress)(nil),              // 22: scql.pb.JobProgress
	(Rr22Mode)(0),                    // 23: scql.pb.Rr22Mode
	(*emptypb.Empty)(nil),            // 24: google.protobuf.Empty
}
var file_api_engine_proto_depIdxs = []int32{
	11, // 0: scql.pb.JobStartParams.parties:type_name -> scql.pb.JobStartParams.Party
	13, // 1: scql.pb.JobStartParams.spu_runtime_cfg:type_name -> spu.pb.RuntimeConfig
	14, // 2: scql.pb.JobStartParams.link_cfg:type_name -> scql.pb.LinkConfig
	15, // 3: scql.pb.JobStartParams.psi_cfg:type_name -> scql.pb.PsiConfig
	16, // 4: scql.pb.JobStartParams.log_cfg:type_name -> scql.pb.LogConfig
	12, // 5: scql.pb.GraphChecksum.sub_graph_checksums:type_name -> scql.pb.GraphChecksum.SubGraphChecksumsEntry
	1,  // 6: scql.pb.RunExecutionPlanRequest.job_params:type_name -> scql.pb.JobStartParams
	17, // 7: scql.pb.RunExecutionPlanRequest.graph:type_name -> scql.pb.SubGraph
	2,  // 8: scql.pb.RunExecutionPlanRequest.graph_checksum:type_name -> scql.pb.GraphChecksum
	18, // 9: scql.pb.RunExecutionPlanRequest.debug_opts:type_name -> scql.pb.DebugOptions
	19, // 10: scql.pb.RunExecutionPlanResponse.status:type_name -> scql.pb.Status
	20, // 11: scql.pb.RunExecutionPlanResponse.out_columns:type_name -> scql.pb.Tensor
	19, // 12: scql.pb.QueryJobStatusResponse.status:type_name -> scql.pb.Status
	21, // 13: scql.pb.QueryJobStatusResponse.job_state:type_name -> scql.pb.JobState
	22, // 14: scql.pb.QueryJobStatusResponse.progress:type_name -> scql.pb.JobProgress
	19, // 15: scql.pb.ReportRequest.status:type_name -> scql.pb.Status
	20, // 16: scql.pb.ReportRequest.out_columns:type_name -> scql.pb.Tensor
	23, // 17: scql.pb.PsiOptions.rr22_mode:type_name -> scql.pb.Rr22Mode
	8,  // 18: scql.pb.NegotiationOptions.streaming_options:type_name -> scql.pb.StreamingOptions
	9,  // 19: scql.pb.NegotiationOptions.psi_options:type_name -> scql.pb.PsiOptions
	3,  // 20: scql.pb.SCQLEngineService.RunExecutionPlan:input_type -> scql.pb.RunExecutionPlanRequest
	5,  // 21: scql.pb.SCQLEngineService.QueryJobStatus:input_type -> scql.pb.QueryJobStatusRequest
	0,  // 22: scql.pb.SCQLEngineService.StopJob:input_type -> scql.pb.StopJobRequest
	7,  // 23: scql.pb.EngineResultCallback.Report:input_type -> scql.pb.ReportRequest
	4,  // 24: scql.pb.SCQLEngineService.RunExecutionPlan:output_type -> scql.pb.RunExecutionPlanResponse
	6,  // 25: scql.pb.SCQLEngineService.QueryJobStatus:output_type -> scql.pb.QueryJobStatusResponse
	19, // 26: scql.pb.SCQLEngineService.StopJob:output_type -> scql.pb.Status
	24, // 27: scql.pb.EngineResultCallback.Report:output_type -> google.protobuf.Empty
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_engine_proto_init() }
func file_api_engine_proto_init() {
	if File_api_engine_proto != nil {
		return
	}
	file_api_common_proto_init()
	file_api_core_proto_init()
	file_api_status_proto_init()
	file_api_subgraph_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_engine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_engine_proto_goTypes,
		DependencyIndexes: file_api_engine_proto_depIdxs,
		MessageInfos:      file_api_engine_proto_msgTypes,
	}.Build()
	File_api_engine_proto = out.File
	file_api_engine_proto_rawDesc = nil
	file_api_engine_proto_goTypes = nil
	file_api_engine_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SCQLEngineServiceClient is the client API for SCQLEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SCQLEngineServiceClient interface {
	// Run the whole execution plan
	RunExecutionPlan(ctx context.Context, in *RunExecutionPlanRequest, opts ...grpc.CallOption) (*RunExecutionPlanResponse, error)
	// Query Job Status
	QueryJobStatus(ctx context.Context, in *QueryJobStatusRequest, opts ...grpc.CallOption) (*QueryJobStatusResponse, error)
	// Stop Job
	StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*Status, error)
}

type sCQLEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSCQLEngineServiceClient(cc grpc.ClientConnInterface) SCQLEngineServiceClient {
	return &sCQLEngineServiceClient{cc}
}

func (c *sCQLEngineServiceClient) RunExecutionPlan(ctx context.Context, in *RunExecutionPlanRequest, opts ...grpc.CallOption) (*RunExecutionPlanResponse, error) {
	out := new(RunExecutionPlanResponse)
	err := c.cc.Invoke(ctx, "/scql.pb.SCQLEngineService/RunExecutionPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sCQLEngineServiceClient) QueryJobStatus(ctx context.Context, in *QueryJobStatusRequest, opts ...grpc.CallOption) (*QueryJobStatusResponse, error) {
	out := new(QueryJobStatusResponse)
	err := c.cc.Invoke(ctx, "/scql.pb.SCQLEngineService/QueryJobStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sCQLEngineServiceClient) StopJob(ctx context.Context, in *StopJobRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/scql.pb.SCQLEngineService/StopJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SCQLEngineServiceServer is the server API for SCQLEngineService service.
type SCQLEngineServiceServer interface {
	// Run the whole execution plan
	RunExecutionPlan(context.Context, *RunExecutionPlanRequest) (*RunExecutionPlanResponse, error)
	// Query Job Status
	QueryJobStatus(context.Context, *QueryJobStatusRequest) (*QueryJobStatusResponse, error)
	// Stop Job
	StopJob(context.Context, *StopJobRequest) (*Status, error)
}

// UnimplementedSCQLEngineServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSCQLEngineServiceServer struct {
}

func (*UnimplementedSCQLEngineServiceServer) RunExecutionPlan(context.Context, *RunExecutionPlanRequest) (*RunExecutionPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunExecutionPlan not implemented")
}
func (*UnimplementedSCQLEngineServiceServer) QueryJobStatus(context.Context, *QueryJobStatusRequest) (*QueryJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryJobStatus not implemented")
}
func (*UnimplementedSCQLEngineServiceServer) StopJob(context.Context, *StopJobRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopJob not implemented")
}

func RegisterSCQLEngineServiceServer(s *grpc.Server, srv SCQLEngineServiceServer) {
	s.RegisterService(&_SCQLEngineService_serviceDesc, srv)
}

func _SCQLEngineService_RunExecutionPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunExecutionPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCQLEngineServiceServer).RunExecutionPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scql.pb.SCQLEngineService/RunExecutionPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCQLEngineServiceServer).RunExecutionPlan(ctx, req.(*RunExecutionPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SCQLEngineService_QueryJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCQLEngineServiceServer).QueryJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scql.pb.SCQLEngineService/QueryJobStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCQLEngineServiceServer).QueryJobStatus(ctx, req.(*QueryJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SCQLEngineService_StopJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCQLEngineServiceServer).StopJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scql.pb.SCQLEngineService/StopJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCQLEngineServiceServer).StopJob(ctx, req.(*StopJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SCQLEngineService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scql.pb.SCQLEngineService",
	HandlerType: (*SCQLEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunExecutionPlan",
			Handler:    _SCQLEngineService_RunExecutionPlan_Handler,
		},
		{
			MethodName: "QueryJobStatus",
			Handler:    _SCQLEngineService_QueryJobStatus_Handler,
		},
		{
			MethodName: "StopJob",
			Handler:    _SCQLEngineService_StopJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/engine.proto",
}

// EngineResultCallbackClient is the client API for EngineResultCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineResultCallbackClient interface {
	// Engine report the plan result to driver(for example, broker)
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type engineResultCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineResultCallbackClient(cc grpc.ClientConnInterface) EngineResultCallbackClient {
	return &engineResultCallbackClient{cc}
}

func (c *engineResultCallbackClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scql.pb.EngineResultCallback/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineResultCallbackServer is the server API for EngineResultCallback service.
type EngineResultCallbackServer interface {
	// Engine report the plan result to driver(for example, broker)
	Report(context.Context, *ReportRequest) (*emptypb.Empty, error)
}

// UnimplementedEngineResultCallbackServer can be embedded to have forward compatible implementations.
type UnimplementedEngineResultCallbackServer struct {
}

func (*UnimplementedEngineResultCallbackServer) Report(context.Context, *ReportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterEngineResultCallbackServer(s *grpc.Server, srv EngineResultCallbackServer) {
	s.RegisterService(&_EngineResultCallback_serviceDesc, srv)
}

func _EngineResultCallback_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineResultCallbackServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scql.pb.EngineResultCallback/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineResultCallbackServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EngineResultCallback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scql.pb.EngineResultCallback",
	HandlerType: (*EngineResultCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _EngineResultCallback_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/engine.proto",
}
