set +ex

docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl create project --project-id \"vldb_test\" --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl invite bob --project-id \"vldb_test\" --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl process invitation 1 --response \"accept\" --project-id \"vldb_test\" --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl create table alice_lineitem --project-id \"vldb_test\" --columns \"l_extendedprice float, l_discount float, l_shipdate datetime, l_quantity float, l_tax float, l_returnflag string, l_linestatus string, l_orderkey int, l_receiptdate datetime, l_commitdate datetime, l_shipmode string, l_shipmode1 string, l_partkey int\" --ref-table alice.lineitem --db-type mysql --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl create table bob_lineitem --project-id \"vldb_test\" --columns \"l_extendedprice float, l_discount float, l_shipdate datetime, l_quantity float, l_tax float, l_returnflag string, l_linestatus string, l_orderkey int, l_partkey int\" --ref-table bob.lineitem --db-type mysql --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl create table bob_part --project-id \"vldb_test\" --columns \"p_type string, p_partkey int\" --ref-table bob.part --db-type mysql --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl create table bob_orders --project-id \"vldb_test\" --columns \"o_orderkey int, o_orderpriority string\" --ref-table bob.orders --db-type mysql --host http://localhost:8080"

# alice set CCL
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_extendedprice --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_discount --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_quantity --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_tax --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_returnflag --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_linestatus --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_receiptdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_commitdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipmode --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipmode1 --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_partkey --host http://localhost:8080"

docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_extendedprice --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_discount --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_quantity --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_tax --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_GROUP_BY --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_returnflag --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_GROUP_BY --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_linestatus --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_receiptdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_commitdate --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_GROUP_BY --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipmode --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_shipmode1 --host http://localhost:8080"
docker exec -it vldb-broker_alice-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name alice_lineitem --column-name l_partkey --host http://localhost:8080"

# bob set ccl

docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_extendedprice --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_discount --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_shipdate --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_quantity --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_tax --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_returnflag --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_linestatus --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_partkey --host http://localhost:8080"

docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_extendedprice --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_discount --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_shipdate --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_quantity --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_AGGREGATE --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_tax --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_GROUP_BY --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_returnflag --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_GROUP_BY --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_linestatus --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name bob_lineitem --column-name l_partkey --host http://localhost:8080"

docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_part --column-name p_type --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_part --column-name p_partkey --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT --project-id \"vldb_test\" --table-name bob_part --column-name p_type --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name bob_part --column-name p_partkey --host http://localhost:8080"

docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_orders --column-name o_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant bob PLAINTEXT --project-id \"vldb_test\" --table-name bob_orders --column-name o_orderpriority --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_JOIN --project-id \"vldb_test\" --table-name bob_orders --column-name o_orderkey --host http://localhost:8080"
docker exec -it vldb-broker_bob-1 bash -c "/home/admin/bin/brokerctl grant alice PLAINTEXT_AFTER_COMPARE --project-id \"vldb_test\" --table-name bob_orders --column-name o_orderpriority --host http://localhost:8080"
