version: '3.8'
services:
  broker_alice:
    image: ${SCQL_IMAGE:-secretflow/scql:latest}
    command:
      - /home/admin/bin/broker
      - -config=/home/admin/configs/config.yml
    restart: always
    ports:
      - mode: host
        protocol: tcp
        published: ${ALICE_PORT:-8081}
        target: 8080
    volumes:
      - ./broker/alice/conf/:/home/admin/configs/
  broker_bob:
    image: ${SCQL_IMAGE:-secretflow/scql:latest}
    command:
      - /home/admin/bin/broker
      - -config=/home/admin/configs/config.yml
    restart: always
    ports:
      - mode: host
        protocol: tcp
        published: ${BOB_PORT:-8082}
        target: 8080
    volumes:
      - ./broker/bob/conf/:/home/admin/configs/
  engine_alice:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    image: ${SCQL_IMAGE:-secretflow/scql:latest}
    volumes:
      - ./engine/alice/conf/gflags.conf:/home/admin/engine/conf/gflags.conf
      - ./engine/alice/conf/ed25519key.pem:/home/admin/engine/conf/ed25519key.pem
      - ./engine/alice/conf/authorized_profile.json:/home/admin/engine/conf/authorized_profile.json
  engine_bob:
    cap_add:
      - NET_ADMIN
    command:
      - /home/admin/bin/scqlengine
      - --flagfile=/home/admin/engine/conf/gflags.conf
    image: ${SCQL_IMAGE:-secretflow/scql:latest}
    volumes:
      - ./engine/bob/conf/gflags.conf:/home/admin/engine/conf/gflags.conf
      - ./engine/bob/conf/ed25519key.pem:/home/admin/engine/conf/ed25519key.pem
      - ./engine/bob/conf/authorized_profile.json:/home/admin/engine/conf/authorized_profile.json
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=__MYSQL_ROOT_PASSWD__
      - TZ=Asia/Shanghai
    healthcheck:
      retries: 10
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - mysql
      timeout: 20s
    expose:
      - "3306"
    restart: always
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d
