// Copyright 2025 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <optional>
#include <string>

#include "dataproxy_sdk/data_proxy_stream.h"

#include "proto/data_proxy_pb.pb.h"

namespace scql::engine::util {
// Unmarshal string generated by proto.Marshal
std::optional<dataproxy_sdk::pb::UploadInfo> ParseUploadInfoFromString(
    const std::string& serialized_upload_info_str);

dataproxy_sdk::proto::UploadInfo ConvertProtoToClass(
    const dataproxy_sdk::pb::UploadInfo& source_upload_info);

void ResetColumnsFromSchema(const std::shared_ptr<arrow::Schema>& schema,
                            dataproxy_sdk::proto::UploadInfo& upload_info);

std::string ArrowToKusciaType(const std::shared_ptr<arrow::DataType>& dtype);

}  // namespace scql::engine::util