---
name: Python Linter
on:
  push:
    branches:
    - main
    paths:
      - '**.py'
  pull_request:
    branches:
    - main
    paths:
      - '**.py'
permissions:
  contents: read
jobs:
  python-linter:
    uses: secretflow/.github/.github/workflows/python-linter.yml@main