---
name: Go Vulnerability Check

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - '.govulncheck.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - '.govulncheck.yml'

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.24
           go-package: ./...
           go-version-file: 'go.mod'
           output-format: 'text'