name: Trigger CircleCI Release

on:
  release:
    types: [published]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Trigger CircleCI Pipeline
        run: |
          run: |
          echo "Release ${{ github.event.release.tag_name }} was published. Triggering CircleCI pipeline..."

          curl -X POST \
            --url "https://circleci.com/api/v2/project/github/secretflow/scql/pipeline/run" \
            --header "Content-Type: application/json" \
            --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
            --data '{"definition_id":"4f50aed3-1fd9-4a64-912b-5fc80e2aa5f2","config":{"branch":"main"},"checkout":{"tag":"${{ github.event.release.tag_name }}"}}'
