name: "Monthly Trigger for CircleCI Regtest"

on:
  schedule:
    # cron: minute hour day month day-of-week
    # Trigger at 08:00 UTC on the 1st day of every month
    - cron: '5 9 1 * *'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Monthly Pipeline
        run: |
          echo "Scheduled monthly trigger fired. Triggering CircleCI pipeline for main branch..."

          curl -X POST \
            --url "https://circleci.com/api/v2/project/github/secretflow/scql/pipeline/run" \
            --header "Content-Type: application/json" \
            --header "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
            --data '{"definition_id":"c6f435ca-697f-488c-83da-156862bb7392","config":{"branch":"main"},"checkout":{"branch":"main"},"parameters":{"enable_regtest":true}}'
