---
name: "Publish Python Package"
on:
  release:
    types: [published]
permissions: read-all
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: secretflow-scql-deploy
        id: secretflow-scql-deploy
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
